### ISSUE TITLE
BWEM Fixes

### ISSUE THREAD

**Issue by JasperGeurtz** [JavaBWAPI/JBWAPI#27]
- [x] Fix Sparkle (https://github.com/N00byEdge/BWEM-community/commit/e6ca66a228caefd437d222a5db2cfa1edcc0ddf8)
 - [ ] Fix Hitchhiker
 - [x] Aztec (KSL)

Fixes welcome!

**Comment by JasperGeurtz** [comment]
Seems to still crash:
```
Sparkle 1.1
java.lang.IllegalStateException: Stacked Neutral objects not aligned: top=bwem.unit.Mineral@24, this=[126, 113]
	at bwem.unit.NeutralImpl.putOnTiles(NeutralImpl.java:171)
	at bwem.unit.NeutralImpl.<init>(NeutralImpl.java:45)
	at bwem.unit.Resource.<init>(Resource.java:23)
	at bwem.unit.Mineral.<init>(Mineral.java:24)
	at bwem.unit.NeutralDataImpl.<init>(NeutralDataImpl.java:37)
	at bwem.map.MapInitializerImpl.initializeNeutralData(MapInitializerImpl.java:100)
	at bwem.map.MapInitializerImpl.initialize(MapInitializerImpl.java:47)
	at bwem.BWEM.initialize(BWEM.java:42)
```

**Comment by Jabbo16** [comment]
I also found problems on Hitchhiker and Aztec KSL edition:

https://github.com/Jabbo16/Ecgberht/blob/master/src/ecgberht/Ecgberht.java#L343-L348

**Comment by JasperGeurtz** [comment]
Thanks for notifying! If anyone is interested in diving deeper into these, fixes are very welcome

**Comment by JasperGeurtz** [comment]
Closed in https://github.com/JavaBWAPI/JBWAPI/tree/bwem-fixes
