### ISSUE TITLE
BWEM IllegalStateException on game start

### ISSUE THREAD

**Issue by dgant** [JavaBWAPI/JBWAPI#51]
Using release 1.2
I have only observed this when playing consecutive games without restarting.

```
cause = {IllegalStateException@5560} "java.lang.IllegalStateException: "
stackTrace = {StackTraceElement[21]@5571} 
 0 = {StackTraceElement@5574} "bwem.Asserter.throwIllegalStateException(Asserter.java:13)"
 1 = {StackTraceElement@5575} "bwem.TerrainData.getTile(TerrainData.java:42)"
 2 = {StackTraceElement@5576} "bwem.TerrainData.getTile(TerrainData.java:49)"
 3 = {StackTraceElement@5577} "bwem.Neutral.putOnTiles(Neutral.java:157)"
 4 = {StackTraceElement@5578} "bwem.Neutral.<init>(Neutral.java:44)"
 5 = {StackTraceElement@5579} "bwem.Resource.<init>(Resource.java:22)"
 6 = {StackTraceElement@5580} "bwem.Mineral.<init>(Mineral.java:23)"
 7 = {StackTraceElement@5581} "bwem.NeutralData.<init>(NeutralData.java:38)"
 8 = {StackTraceElement@5582} "bwem.BWMapInitializer.initializeNeutralData(BWMapInitializer.java:93)"
 9 = {StackTraceElement@5583} "bwem.BWMapInitializer.initialize(BWMapInitializer.java:42)"
 10 = {StackTraceElement@5584} "bwem.BWEM.initialize(BWEM.java:53)"
 11 = {StackTraceElement@5585} "bwta.BWTA.analyze(BWTA.java:51)"
```

PurpleWave is configured to do analysis with assertions on, then to retry them with assertions off if anything goes wrong. Re-analyzing without assertions produced data that looked mostly correct.

I suspect (but haven't tested) that the issue occurs when playing a game on a map that's smaller in at least one dimension than the previous one. I noticed the error occurred at least once on a tile with X==124 on https://liquipedia.net/starcraft/Tres_Pass which is only 120 tiles wide.

**Comment by dgant** [comment]
Hmm, got another, slightly different one. This was on Fighting Spirit:
```
exception = {IllegalStateException@5490} "java.lang.IllegalStateException: "
 detailMessage = ""
 cause = {IllegalStateException@5490} "java.lang.IllegalStateException: "
 stackTrace = {StackTraceElement[17]@5502} 
  0 = {StackTraceElement@5505} "bwem.Asserter.throwIllegalStateException(Asserter.java:13)"
  1 = {StackTraceElement@5506} "bwem.BWMap.breadthFirstSearch(BWMap.java:335)"
  2 = {StackTraceElement@5507} "bwem.BWMap.breadthFirstSearch(BWMap.java:341)"
  3 = {StackTraceElement@5508} "bwem.ChokePoint.<init>(ChokePoint.java:108)"
  4 = {StackTraceElement@5509} "bwem.Graph.createChokePoints(Graph.java:346)"
  5 = {StackTraceElement@5510} "bwem.BWMapInitializer.initialize(BWMapInitializer.java:60)"
  6 = {StackTraceElement@5511} "bwem.BWEM.initialize(BWEM.java:53)"
  7 = {StackTraceElement@5512} "bwta.BWTA.analyze(BWTA.java:51)"
```

**Comment by JasperGeurtz** [comment]
I can reproduce

```
Game table mapping not found.
Game table mapping not found.
Game table mapping not found.
Game table mapping not found.
0 | 5552 | 0 | 2481218
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Connected
Connection successful
map: | iCCup | Fighting Spirit 1.3
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
map: ÅÂ¾çÀÇ Á¦±¹ 1.0
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
map: La Mancha 1.1
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
map: Jade 1.0
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
map: Electric Circuit
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
map: Icarus 1.0
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
map: La Mancha 1.1
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
map: | iCCup | MoonGlaive 2.1
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
map: Andromeda 1.0
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
map: Roadrunner_SE 1.2
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
map: Destination 1.1
WARNING: this BWTA is fake and only translates BWTA calls to their respective BWEM calls. Please use BWEM directly if possible.
Exception in thread "main" java.lang.IllegalStateException: 
	at bwem.Asserter.throwIllegalStateException(Asserter.java:13)
	at bwem.TerrainData.getTile(TerrainData.java:42)
	at bwem.TerrainData.getTile(TerrainData.java:49)
	at bwem.Neutral.putOnTiles(Neutral.java:157)
	at bwem.Neutral.<init>(Neutral.java:44)
	at bwem.Resource.<init>(Resource.java:22)
	at bwem.Mineral.<init>(Mineral.java:23)
	at bwem.NeutralData.<init>(NeutralData.java:38)
	at bwem.BWMapInitializer.initializeNeutralData(BWMapInitializer.java:93)
	at bwem.BWMapInitializer.initialize(BWMapInitializer.java:42)
	at bwem.BWEM.initialize(BWEM.java:53)
	at bwta.BWTA.analyze(BWTA.java:51)
	at MapListener.onStart(MapListener.java:16)
	at bwapi.EventHandler.operation(EventHandler.java:23)
	at bwapi.Client.update(Client.java:239)
	at bwapi.BWClient.startGame(BWClient.java:43)
	at MapListener.main(MapListener.java:24)

Process finished with exit code 1
```

Investigating

**Comment by JasperGeurtz** [comment]
<img width="1081" alt="error" src="https://user-images.githubusercontent.com/10107858/73929327-df9b8780-48d4-11ea-94a6-f65bfb725159.png">
It is indeed related to the mapsize it seems, but can't figure out why yet why it is querying that tile

**Comment by JasperGeurtz** [comment]
<img width="816" alt="error2" src="https://user-images.githubusercontent.com/10107858/73930200-73ba1e80-48d6-11ea-999b-67e84db6defb.png">
<img width="809" alt="error3" src="https://user-images.githubusercontent.com/10107858/73930212-761c7880-48d6-11ea-8925-ad4c61676d45.png">

This is all queried directly from the BWAPI Server.

Somehow a Unit (Mineral) exists outside of the map bounds

**Comment by dgant** [comment]
Closing as ghost units are the best explanation and outside of JBWAPI's ability to fix.
