### ISSUE TITLE
Crashes in init on playing a replay

### ISSUE THREAD

**Issue by JasperGeurtz** [JavaBWAPI/JBWAPI#57]
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
    at bwapi.Game.init(Game.java:185)
    at bwapi.EventHandler.operation(EventHandler.java:21)
    at bwapi.Client.update(Client.java:239)
    at bwapi.BWClient.startGame(BWClient.java:43)
    at bwapi.BWClient.startGame(BWClient.java:25)
    at exec.ExampleBot.run(ExampleBot.java:23)
    at exec.ExampleBot.main(ExampleBot.java:27)
```

```Java
enemy = players[gameData.getEnemy()] = -1
```

**Comment by JasperGeurtz** [comment]
Fixed in https://github.com/JavaBWAPI/JBWAPI/commit/010e26cd001c152eb130101443b2218455cb02ea
